---
title: "scratch"
output: html_document
---


```{r}
Sys.setenv(DEBUGME = "pkglock")

library(pkglock)
```

```{r eval=FALSE}
pkgs <- c("dplyr", "ggplot2 (>= 2.2.1.9000)", "purrr", "PKPDmisc")
runtime_desc <- gen_runtime_description(
  pkgs,
  github = c("tidyverse/ggplot2"),
  name = "Devin Pastoor",
  email = "devin.pastoor@gmail.com"
)
```

```{r}
pkgs <- c(
  "purrr",
"covr",
"dplyr (>= 0.4.3)",
"knitr",
"rmarkdown",
"testthat (>= 0.11.0)",
"debugme",
"fs",
"mockery",
"pingr",
"ggplot2movies",
"hexbin",
"Hmisc",
"mapproj",
"maptools",
"multcomp",
"nlme",
"nlme",
"vdiffr",
"quantreg"
)
runtime_desc <- gen_runtime_description(
  pkgs,
  name = "Devin Pastoor",
  email = "devin.pastoor@gmail.com"
)

runtime_desc
```

## using package functions

```{r}
tmpdir <- "tmp"
fs::dir_create(tmpdir)
```


```{r}
new_snap <- install_from_desc(runtime_desc, .dir = tmpdir)
```

```{r}
new_snap$pkglibpath
```

```{r}
new_snap$snapshot$tardir
```


here should probably copy both the binaries (optimization) and the tarballs
(req) into the new runtime template. The binaries may be in other libs
on the system.

```{r}
rtdir <- setup_runtime_template(new_snap$snapshot$lockfile, .dir = tmpdir)
```

```{r}
## copy over tars + binaries at least in the libpath

fs::dir_copy(new_snap$snapshot$tardir, fs::path(rtdir, "packrat"))
# if going to do this, will need to get the full platform spec correct
# eg x86_64-apple-darwin16.7.0/3.4.3/<libs>
new_binary_dir <- fs::path(rtdir, 
          "packrat", 
          "lib", 
          R.version$platform)
fs::dir_create(new_binary_dir)

fs::dir_copy(new_snap$pkglibpath, new_binary_dir) 
# is there a way to copy the contents of a dir with renaming

file.rename(fs::path(new_binary_dir, "pkglib"), fs::path(new_binary_dir, getRversion()))
```

```{r}
binary_runtime <- install_runtime(rtdir)
```

```{r}
.libPaths()
```










